"""Add documents, notes, note_links, workouts, and exercise_entries tables

Revision ID: f1c8b3e6a9d2
Revises: e2f9a4c7b5d1
Create Date: 2026-05-05

Phase 3 new domains — all five tables are new; none existed before.

documents
---------
Long-form content edited in BlockNote. Dual storage: source_markdown is
always kept in sync with editor_json so the content is readable outside the
editor. Slugs are unique within a household and auto-generated by the service
layer from the title. parent_id enables page hierarchies (e.g. a subpage
inside a project page). archived_at is a soft-delete; the list endpoint
filters archived docs by default. description is a short prose summary read
by the AI agent to locate relevant notes before generating a document brief.
kind: page | template  (journal is handled by the notes table, not documents)

notes
-----
Short-form, atomic, Zettelkasten-style notes and journal entries. body is
plain markdown — no BlockNote JSON. kind: note | journal. journaled_date is
set when kind = 'journal' and drives the daily-journal query. archived_at
mirrors the documents soft-delete pattern. Tags are applied via the existing
taggings table (entity_type = 'note').

note_links
----------
Directed adjacency table for the Zettelkasten knowledge graph. One row per
explicit link from a source note to a target note. Both FKs cascade on
delete so stale links never accumulate. The (source, target) pair is unique
— duplicate links are rejected at the DB level.

workouts
--------
One row per training session. name is optional (many sessions are unnamed).
workout_date drives ordering and the daily-journal query pattern.

exercise_entries
----------------
Ordered line items within a workout. metrics JSONB shape varies by type:
  strength   → {sets, reps, weight_kg}
  cardio     → {duration_seconds, distance_meters, avg_heart_rate}
  hiit       → {rounds, work_seconds, rest_seconds}
  flexibility / other → freeform keys
sort_order controls display sequence within a workout.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID

revision: str = "f1c8b3e6a9d2"
down_revision: Union[str, None] = "e2f9a4c7b5d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── documents ─────────────────────────────────────────────────────────────
    # document_kind, note_kind, and exercise_type enums are owned by their
    # respective table columns below (create_type=True). Using op.execute to
    # pre-create types and create_type=False causes _on_table_create to fire
    # again on the column regardless, producing a duplicate-type error.
    op.create_table(
        "documents",
        sa.Column(
            "id", UUID(as_uuid=True), primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "parent_id", UUID(as_uuid=True),
            sa.ForeignKey("documents.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column(
            "household_id", UUID(as_uuid=True),
            sa.ForeignKey("households.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "created_by_user_id", UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column(
            "kind",
            sa.Enum("page", "template", name="document_kind", create_type=True),
            nullable=False,
            server_default="page",
        ),
        sa.Column("source_markdown", sa.Text(), nullable=True),
        sa.Column("editor_json", JSONB(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
        sa.UniqueConstraint("household_id", "slug", name="documents_household_slug_key"),
    )
    op.create_index("idx_documents_household_id", "documents", ["household_id"])
    op.create_index("idx_documents_parent_id", "documents", ["parent_id"])
    op.execute(
        "CREATE TRIGGER documents_updated_at BEFORE UPDATE ON documents "
        "FOR EACH ROW EXECUTE FUNCTION update_updated_at()"
    )

    # ── notes ─────────────────────────────────────────────────────────────────
    op.create_table(
        "notes",
        sa.Column(
            "id", UUID(as_uuid=True), primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "household_id", UUID(as_uuid=True),
            sa.ForeignKey("households.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "created_by_user_id", UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column(
            "kind",
            sa.Enum("note", "journal", name="note_kind", create_type=True),
            nullable=False,
            server_default="note",
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("journaled_date", sa.Date(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
    )
    op.create_index("idx_notes_household_id", "notes", ["household_id"])
    op.create_index("idx_notes_kind", "notes", ["kind"])
    # Efficient date-range queries for journal entries (e.g. "this week's journals")
    op.create_index("idx_notes_journaled_date", "notes", ["journaled_date"])
    op.execute(
        "CREATE TRIGGER notes_updated_at BEFORE UPDATE ON notes "
        "FOR EACH ROW EXECUTE FUNCTION update_updated_at()"
    )

    # ── note_links ────────────────────────────────────────────────────────────
    # Directed edges in the Zettelkasten knowledge graph.
    # Both ends CASCADE: when either note is deleted, the link is removed.
    op.create_table(
        "note_links",
        sa.Column(
            "id", UUID(as_uuid=True), primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "source_note_id", UUID(as_uuid=True),
            sa.ForeignKey("notes.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "target_note_id", UUID(as_uuid=True),
            sa.ForeignKey("notes.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
        sa.UniqueConstraint(
            "source_note_id", "target_note_id",
            name="note_links_source_target_key",
        ),
    )
    # Forward links: "what does this note link to?"
    op.create_index("idx_note_links_source", "note_links", ["source_note_id"])
    # Backlinks: "what notes link to this note?"
    op.create_index("idx_note_links_target", "note_links", ["target_note_id"])

    # ── workouts ──────────────────────────────────────────────────────────────
    op.create_table(
        "workouts",
        sa.Column(
            "id", UUID(as_uuid=True), primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "household_id", UUID(as_uuid=True),
            sa.ForeignKey("households.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "created_by_user_id", UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("workout_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
    )
    op.create_index("idx_workouts_household_id", "workouts", ["household_id"])
    op.create_index("idx_workouts_workout_date", "workouts", ["workout_date"])
    op.execute(
        "CREATE TRIGGER workouts_updated_at BEFORE UPDATE ON workouts "
        "FOR EACH ROW EXECUTE FUNCTION update_updated_at()"
    )

    # ── exercise_entries ──────────────────────────────────────────────────────
    op.create_table(
        "exercise_entries",
        sa.Column(
            "id", UUID(as_uuid=True), primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "workout_id", UUID(as_uuid=True),
            sa.ForeignKey("workouts.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "strength", "cardio", "hiit", "flexibility", "other",
                name="exercise_type", create_type=True,
            ),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        # Shape varies by type — see module docstring above.
        sa.Column("metrics", JSONB(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
    )
    op.create_index("idx_exercise_entries_workout_id", "exercise_entries", ["workout_id"])
    op.execute(
        "CREATE TRIGGER exercise_entries_updated_at BEFORE UPDATE ON exercise_entries "
        "FOR EACH ROW EXECUTE FUNCTION update_updated_at()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS exercise_entries_updated_at ON exercise_entries")
    op.drop_table("exercise_entries")

    op.execute("DROP TRIGGER IF EXISTS workouts_updated_at ON workouts")
    op.drop_table("workouts")

    op.drop_table("note_links")

    op.execute("DROP TRIGGER IF EXISTS notes_updated_at ON notes")
    op.drop_table("notes")

    op.execute("DROP TRIGGER IF EXISTS documents_updated_at ON documents")
    op.drop_table("documents")

    op.execute("DROP TYPE IF EXISTS exercise_type")
    op.execute("DROP TYPE IF EXISTS note_kind")
    op.execute("DROP TYPE IF EXISTS document_kind")
